import React from 'react';
import log from '../../changelog.json';
import { colors as s, fmt } from '../_lib';

export default { title: 'Foundations/Changelog', parameters: { layout: 'fullscreen' } };

const isColor = (v: any) => typeof v === 'string' && /^(#|rgb|hsl)/.test(v);

function Value({ v }: { v: any }) {
  if (v == null) return <span style={s.mono}>—</span>;
  if (isColor(v)) {
    return (
      <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
        <span style={{ width: 16, height: 16, borderRadius: 4, background: v, border: '1px solid rgba(0,0,0,0.1)' }} />
        <code style={s.mono}>{v}</code>
      </span>
    );
  }
  return <code style={s.mono}>{fmt(v)}</code>;
}

function Group({ title, items, render }: { title: string; items: any[]; render: (i: any) => React.ReactNode }) {
  if (!items?.length) return null;
  return (
    <div style={{ marginTop: 16 }}>
      <h4 style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.06em', color: '#5d6a85', margin: '0 0 8px' }}>
        {title} ({items.length})
      </h4>
      <div style={{ display: 'grid', gap: 6 }}>{items.map((i, idx) => <React.Fragment key={idx}>{render(i)}</React.Fragment>)}</div>
    </div>
  );
}

export const History = () => {
  const entries = log as any[];
  return (
    <div style={s.page}>
      <h1>Changelog</h1>
      <p style={{ color: '#5d6a85', maxWidth: 640 }}>
        Token-level diffs generated by <code>npm run changelog</code> after each sync from Figma.
      </p>
      {entries.length === 0 && <p style={{ color: '#5d6a85' }}>No entries yet. Run <code>npm run sync</code> to record one.</p>}
      {entries.map((entry, i) => (
        <section key={i} style={{ ...s.card, marginBottom: 24 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
            <h3 style={{ margin: 0 }}>{entry.date}</h3>
            <span style={{ ...s.mono, color: '#5d6a85' }}>{entry.summary}</span>
          </div>
          <Group title="Added" items={entry.added} render={(c) => (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 12, alignItems: 'center' }}>
              <code style={s.mono}>{c.token}</code>
              <Value v={c.value} />
            </div>
          )} />
          <Group title="Changed" items={entry.changed} render={(c) => (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr auto auto auto', gap: 12, alignItems: 'center' }}>
              <code style={s.mono}>{c.token}</code>
              <Value v={c.from} />
              <span>→</span>
              <Value v={c.to} />
            </div>
          )} />
          <Group title="Removed" items={entry.removed} render={(c) => (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr auto', gap: 12, alignItems: 'center', opacity: 0.7 }}>
              <code style={{ ...s.mono, textDecoration: 'line-through' }}>{c.token}</code>
              <Value v={c.value} />
            </div>
          )} />
        </section>
      ))}
    </div>
  );
};
