// Style Dictionary v4 config (ESM). Reads Tokens Studio / DTCG JSON from ./tokens
// (synced from the upstream GitHub repo via `npm run sync`) and emits JS/TS/JSON.
import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

// Registers tokens-studio preprocessor (resolves {alias} references across files,
// expands composite $values, handles math/rgba/etc.) and a bag of transforms.
register(StyleDictionary);

// RN-friendly transform group: no "rem" suffix, numeric dimensions.
StyleDictionary.registerTransformGroup({
  name: 'js/rn',
  transforms: [
    'ts/descriptionToComment',
    'ts/size/px',
    'ts/opacity',
    'ts/size/lineheight',
    'ts/typography/fontWeight',
    'ts/resolveMath',
    'ts/color/modifiers',
    'attribute/cti',
    'name/camel',
    'color/hex',
  ],
});

// Nested JS object format mirroring the shape used by the RN app's theme.js.
StyleDictionary.registerFormat({
  name: 'javascript/nested',
  format: ({ dictionary }) => {
    if (process.env.SD_DEBUG) console.log('DBG sample token:', JSON.stringify(dictionary.allTokens[0], null, 2));
    const tree = {};
    dictionary.allTokens.forEach((t) => {
      const path = t.path || [];
      let node = tree;
      path.forEach((seg, i) => {
        if (i === path.length - 1) node[seg] = t.value ?? t.$value;
        else {
          if (typeof node[seg] !== 'object' || node[seg] === null) node[seg] = {};
          node = node[seg];
        }
      });
    });
    return `// AUTO-GENERATED by Style Dictionary. Do not edit.\nexport default ${JSON.stringify(tree, null, 2)};\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'typescript/nested',
  format: ({ dictionary }) => {
    const tree = {};
    dictionary.allTokens.forEach((t) => {
      let node = tree;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) node[seg] = t.value;
        else node[seg] = node[seg] || {};
      });
    });
    const toType = (obj) => {
      if (obj === undefined) return 'unknown';
      if (typeof obj !== 'object' || obj === null) return JSON.stringify(obj);
      const entries = Object.entries(obj)
        .map(([k, v]) => `  ${JSON.stringify(k)}: ${String(toType(v)).replace(/\n/g, '\n  ')}`)
        .join(';\n');
      return `{\n${entries}\n}`;
    };
    return `// AUTO-GENERATED by Style Dictionary. Do not edit.\nexport declare const tokens: ${toType(tree)};\nexport default tokens;\n`;
  },
});

export default {
  source: ['tokens/**/*.json'],
  preprocessors: ['tokens-studio'],
  platforms: {
    js: {
      transformGroup: 'js/rn',
      buildPath: 'build/js/',
      files: [
        { destination: 'tokens.js', format: 'javascript/nested' },
        { destination: 'tokens.esm.js', format: 'javascript/nested' },
      ],
    },
    ts: {
      transformGroup: 'js/rn',
      buildPath: 'build/ts/',
      files: [{ destination: 'tokens.d.ts', format: 'typescript/nested' }],
    },
    json: {
      transformGroup: 'js/rn',
      buildPath: 'build/json/',
      files: [{ destination: 'tokens.flat.json', format: 'json/flat' }],
    },
  },
};
